
# Unit IDs cf https://github.com/Blizzard/s2client-api/blob/master/include/sc2api/sc2_typeenums.h
_TERRAN_ARMORY = 29
_TERRAN_AUTOTURRET = 31
_TERRAN_BANSHEE = 55
_TERRAN_BARRACKS = 21
_TERRAN_BARRACKSFLYING = 46
_TERRAN_BARRACKSREACTOR = 38
_TERRAN_BARRACKSTECHLAB = 37
_TERRAN_BATTLECRUISER = 57
_TERRAN_BUNKER = 24
_TERRAN_COMMANDCENTER = 18
_TERRAN_COMMANDCENTERFLYING = 36
_TERRAN_CYCLONE = 692
_TERRAN_ENGINEERINGBAY = 22
_TERRAN_FACTORY = 27
_TERRAN_FACTORYFLYING = 43
_TERRAN_FACTORYREACTOR = 40
_TERRAN_FACTORYTECHLAB = 39
_TERRAN_FUSIONCORE = 30
_TERRAN_GHOST = 50
_TERRAN_GHOSTACADEMY = 26
_TERRAN_HELLION = 53
_TERRAN_HELLIONTANK = 484
_TERRAN_LIBERATOR = 689
_TERRAN_LIBERATORAG = 734
_TERRAN_MARAUDER = 51
_TERRAN_MARINE = 48
_TERRAN_MEDIVAC = 54
_TERRAN_MISSILETURRET = 23
_TERRAN_MULE = 268
_TERRAN_ORBITALCOMMAND = 132
_TERRAN_ORBITALCOMMANDFLYING = 134
_TERRAN_PLANETARYFORTRESS = 130
_TERRAN_RAVEN = 56
_TERRAN_REAPER = 49
_TERRAN_REFINERY = 20
_TERRAN_SCV = 45
_TERRAN_SENSORTOWER = 25
_TERRAN_SIEGETANK = 33
_TERRAN_SIEGETANKSIEGED = 32
_TERRAN_STARPORT = 28
_TERRAN_STARPORTFLYING = 44
_TERRAN_STARPORTREACTOR = 42
_TERRAN_STARPORTTECHLAB = 41
_TERRAN_SUPPLYDEPOT = 19
_TERRAN_SUPPLYDEPOTLOWERED = 47
_TERRAN_THOR = 52
_TERRAN_THORAP = 691
_TERRAN_VIKINGASSAULT = 34
_TERRAN_VIKINGFIGHTER = 35
_TERRAN_WIDOWMINE = 498
_TERRAN_WIDOWMINEBURROWED = 500
_TERRAN_KD8CHARGE = 830
_TERRAN_NUKE = 58
_TERRAN_POINTDEFENSEDRONE = 11
_TERRAN_REACTOR = 6
_TERRAN_TECHLAB = 5
_ZERG_BANELING = 9
_ZERG_BANELINGBURROWED = 115
_ZERG_BANELINGCOCOON = 8
_ZERG_BANELINGNEST = 96
_ZERG_BROODLING = 289
_ZERG_BROODLORD = 114
_ZERG_BROODLORDCOCOON = 113
_ZERG_CHANGELING = 12
_ZERG_CHANGELINGMARINE = 15
_ZERG_CHANGELINGMARINESHIELD = 14
_ZERG_CHANGELINGZEALOT = 13
_ZERG_CHANGELINGZERGLING = 17
_ZERG_CHANGELINGZERGLINGWINGS = 16
_ZERG_CORRUPTOR = 112
_ZERG_CREEPTUMOR = 87
_ZERG_CREEPTUMORBURROWED = 137
_ZERG_CREEPTUMORQUEEN = 138
_ZERG_DRONE = 104
_ZERG_DRONEBURROWED = 116
_ZERG_EGG = 103
_ZERG_EVOLUTIONCHAMBER = 90
_ZERG_EXTRACTOR = 88
_ZERG_GREATERSPIRE = 102
_ZERG_HATCHERY = 86
_ZERG_HIVE = 101
_ZERG_HYDRALISK = 107
_ZERG_HYDRALISKBURROWED = 117
_ZERG_HYDRALISKDEN = 91
_ZERG_INFESTATIONPIT = 94
_ZERG_INFESTEDTERRANSEGG = 150
_ZERG_INFESTOR = 111
_ZERG_INFESTORBURROWED = 127
_ZERG_INFESTORTERRAN = 7
_ZERG_LAIR = 100
_ZERG_LARVA = 151
_ZERG_LOCUSTMP = 489
_ZERG_LOCUSTMPFLYING = 693
_ZERG_LURKERDENMP = 504
_ZERG_LURKERMP = 502
_ZERG_LURKERMPBURROWED = 503
_ZERG_LURKERMPEGG = 501
_ZERG_MUTALISK = 108
_ZERG_NYDUSCANAL = 142
_ZERG_NYDUSNETWORK = 95
_ZERG_OVERLORD = 106
_ZERG_OVERLORDCOCOON = 128
_ZERG_OVERLORDTRANSPORT = 893
_ZERG_OVERSEER = 129
_ZERG_QUEEN = 126
_ZERG_QUEENBURROWED = 125
_ZERG_RAVAGER = 688
_ZERG_RAVAGERCOCOON = 687
_ZERG_ROACH = 110
_ZERG_ROACHBURROWED = 118
_ZERG_ROACHWARREN = 97
_ZERG_SPAWNINGPOOL = 89
_ZERG_SPINECRAWLER = 98
_ZERG_SPINECRAWLERUPROOTED = 139
_ZERG_SPIRE = 92
_ZERG_SPORECRAWLER = 99
_ZERG_SPORECRAWLERUPROOTED = 140
_ZERG_SWARMHOSTBURROWEDMP = 493
_ZERG_SWARMHOSTMP = 494
_ZERG_TRANSPORTOVERLORDCOCOON = 892
_ZERG_ULTRALISK = 109
_ZERG_ULTRALISKCAVERN = 93
_ZERG_VIPER = 499
_ZERG_ZERGLING = 105
_ZERG_ZERGLINGBURROWED = 119
_ZERG_PARASITICBOMBDUMMY = 824
_PROTOSS_ADEPT = 311
_PROTOSS_ADEPTPHASESHIFT = 801
_PROTOSS_ARCHON = 141
_PROTOSS_ASSIMILATOR = 61
_PROTOSS_CARRIER = 79
_PROTOSS_COLOSSUS = 4
_PROTOSS_CYBERNETICSCORE = 72
_PROTOSS_DARKSHRINE = 69
_PROTOSS_DARKTEMPLAR = 76
_PROTOSS_DISRUPTOR = 694
_PROTOSS_DISRUPTORPHASED = 733
_PROTOSS_FLEETBEACON = 64
_PROTOSS_FORGE = 63
_PROTOSS_GATEWAY = 62
_PROTOSS_HIGHTEMPLAR = 75
_PROTOSS_IMMORTAL = 83
_PROTOSS_INTERCEPTOR = 85
_PROTOSS_MOTHERSHIP = 10
_PROTOSS_MOTHERSHIPCORE = 488
_PROTOSS_NEXUS = 59
_PROTOSS_OBSERVER = 82
_PROTOSS_ORACLE = 495
_PROTOSS_ORACLESTASISTRAP = 732
_PROTOSS_PHOENIX = 78
_PROTOSS_PHOTONCANNON = 66
_PROTOSS_PROBE = 84
_PROTOSS_PYLON = 60
_PROTOSS_PYLONOVERCHARGED = 894
_PROTOSS_ROBOTICSBAY = 70
_PROTOSS_ROBOTICSFACILITY = 71
_PROTOSS_SENTRY = 77
_PROTOSS_SHIELDBATTERY = 1910
_PROTOSS_STALKER = 74
_PROTOSS_STARGATE = 67
_PROTOSS_TEMPEST = 496
_PROTOSS_TEMPLARARCHIVE = 68
_PROTOSS_TWILIGHTCOUNCIL = 65
_PROTOSS_VOIDRAY = 80
_PROTOSS_WARPGATE = 133
_PROTOSS_WARPPRISM = 81
_PROTOSS_WARPPRISMPHASING = 136
_PROTOSS_ZEALOT = 73
_NEUTRAL_BATTLESTATIONMINERALFIELD = 886
_NEUTRAL_BATTLESTATIONMINERALFIELD750 = 887
_NEUTRAL_COLLAPSIBLEROCKTOWERDEBRIS = 490
_NEUTRAL_COLLAPSIBLEROCKTOWERDIAGONAL = 588
_NEUTRAL_COLLAPSIBLEROCKTOWERPUSHUNIT = 561
_NEUTRAL_COLLAPSIBLETERRANTOWERDEBRIS = 485
_NEUTRAL_COLLAPSIBLETERRANTOWERDIAGONAL = 589
_NEUTRAL_COLLAPSIBLETERRANTOWERPUSHUNIT = 562
_NEUTRAL_COLLAPSIBLETERRANTOWERPUSHUNITRAMPLEFT = 559
_NEUTRAL_COLLAPSIBLETERRANTOWERPUSHUNITRAMPRIGHT = 560
_NEUTRAL_COLLAPSIBLETERRANTOWERRAMPLEFT = 590
_NEUTRAL_COLLAPSIBLETERRANTOWERRAMPRIGHT = 591
_NEUTRAL_DEBRISRAMPLEFT = 486
_NEUTRAL_DEBRISRAMPRIGHT = 487
_NEUTRAL_DESTRUCTIBLEDEBRIS6X6 = 365
_NEUTRAL_DESTRUCTIBLEDEBRISRAMPDIAGONALHUGEBLUR = 377
_NEUTRAL_DESTRUCTIBLEDEBRISRAMPDIAGONALHUGEULBR = 376
_NEUTRAL_DESTRUCTIBLEROCK6X6 = 371
_NEUTRAL_DESTRUCTIBLEROCKEX1DIAGONALHUGEBLUR = 641
_NEUTRAL_FORCEFIELD = 135
_NEUTRAL_KARAKFEMALE = 324
_NEUTRAL_LABMINERALFIELD = 665
_NEUTRAL_LABMINERALFIELD750 = 666
_NEUTRAL_MINERALFIELD = 341
_NEUTRAL_MINERALFIELD750 = 483
_NEUTRAL_PROTOSSVESPENEGEYSER = 608
_NEUTRAL_PURIFIERMINERALFIELD = 884
_NEUTRAL_PURIFIERMINERALFIELD750 = 885
_NEUTRAL_PURIFIERRICHMINERALFIELD = 796
_NEUTRAL_PURIFIERRICHMINERALFIELD750 = 797
_NEUTRAL_PURIFIERVESPENEGEYSER = 880
_NEUTRAL_RICHMINERALFIELD = 146
_NEUTRAL_RICHMINERALFIELD750 = 147
_NEUTRAL_RICHVESPENEGEYSER = 344
_NEUTRAL_SCANTIPEDE = 335
_NEUTRAL_SHAKURASVESPENEGEYSER = 881
_NEUTRAL_SPACEPLATFORMGEYSER = 343
_NEUTRAL_UNBUILDABLEBRICKSDESTRUCTIBLE = 473
_NEUTRAL_UNBUILDABLEPLATESDESTRUCTIBLE = 474
_NEUTRAL_UTILITYBOT = 330
_NEUTRAL_VESPENEGEYSER = 342
_NEUTRAL_XELNAGATOWER = 149


class UnitTypeIds:

    def neutral_mineral_field(self) -> int:
        return _NEUTRAL_MINERALFIELD

    def neutral_vespene_geyser(self) -> int:
        return _NEUTRAL_VESPENEGEYSER

    def terran_barracks(self) -> int:
        return _TERRAN_BARRACKS

    def terran_barracks_techlab(self) -> int:
        return _TERRAN_BARRACKSTECHLAB

    def terran_barracks_reactor(self) -> int:
        return _TERRAN_BARRACKSREACTOR

    def terran_command_center(self) -> int:
        return _TERRAN_COMMANDCENTER

    def terran_orbital_command(self) -> int:
        return _TERRAN_ORBITALCOMMAND

    def terran_factory(self) -> int:
        return _TERRAN_FACTORY

    def terran_scv(self) -> int:
        return _TERRAN_SCV

    def terran_refinery(self) -> int:
        return _TERRAN_REFINERY

    def terran_supply_depot(self) -> int:
        return _TERRAN_SUPPLYDEPOT

    def terran_starport(self) -> int:
        return _TERRAN_STARPORT


class AllUnitTypeIdsPerRace:

    def terran(self) -> []:
        return [
            _TERRAN_ARMORY,
            _TERRAN_AUTOTURRET,
            _TERRAN_BANSHEE,
            _TERRAN_BARRACKS,
            _TERRAN_BARRACKSFLYING,
            _TERRAN_BARRACKSREACTOR,
            _TERRAN_BARRACKSTECHLAB,
            _TERRAN_BATTLECRUISER,
            _TERRAN_BUNKER,
            _TERRAN_COMMANDCENTER,
            _TERRAN_COMMANDCENTERFLYING,
            _TERRAN_CYCLONE,
            _TERRAN_ENGINEERINGBAY,
            _TERRAN_FACTORY,
            _TERRAN_FACTORYFLYING,
            _TERRAN_FACTORYREACTOR,
            _TERRAN_FACTORYTECHLAB,
            _TERRAN_FUSIONCORE,
            _TERRAN_GHOST,
            _TERRAN_GHOSTACADEMY,
            _TERRAN_HELLION,
            _TERRAN_HELLIONTANK,
            _TERRAN_LIBERATOR,
            _TERRAN_LIBERATORAG,
            _TERRAN_MARAUDER,
            _TERRAN_MARINE,
            _TERRAN_MEDIVAC,
            _TERRAN_MISSILETURRET,
            _TERRAN_MULE,
            _TERRAN_ORBITALCOMMAND,
            _TERRAN_ORBITALCOMMANDFLYING,
            _TERRAN_PLANETARYFORTRESS,
            _TERRAN_RAVEN,
            _TERRAN_REAPER,
            _TERRAN_REFINERY,
            _TERRAN_SCV,
            _TERRAN_SENSORTOWER,
            _TERRAN_SIEGETANK,
            _TERRAN_SIEGETANKSIEGED,
            _TERRAN_STARPORT,
            _TERRAN_STARPORTFLYING,
            _TERRAN_STARPORTREACTOR,
            _TERRAN_STARPORTTECHLAB,
            _TERRAN_SUPPLYDEPOT,
            _TERRAN_SUPPLYDEPOTLOWERED,
            _TERRAN_THOR,
            _TERRAN_THORAP,
            _TERRAN_VIKINGASSAULT,
            _TERRAN_VIKINGFIGHTER,
            _TERRAN_WIDOWMINE,
            _TERRAN_WIDOWMINEBURROWED,
            _TERRAN_KD8CHARGE,
            _TERRAN_NUKE,
            _TERRAN_POINTDEFENSEDRONE,
            _TERRAN_REACTOR,
            _TERRAN_TECHLAB,
        ]

    def zerg(self) -> []:
        return [
            _ZERG_BANELING,
            _ZERG_BANELINGBURROWED,
            _ZERG_BANELINGCOCOON,
            _ZERG_BANELINGNEST,
            _ZERG_BROODLING,
            _ZERG_BROODLORD,
            _ZERG_BROODLORDCOCOON,
            _ZERG_CHANGELING,
            _ZERG_CHANGELINGMARINE,
            _ZERG_CHANGELINGMARINESHIELD,
            _ZERG_CHANGELINGZEALOT,
            _ZERG_CHANGELINGZERGLING,
            _ZERG_CHANGELINGZERGLINGWINGS,
            _ZERG_CORRUPTOR,
            _ZERG_CREEPTUMOR,
            _ZERG_CREEPTUMORBURROWED,
            _ZERG_CREEPTUMORQUEEN,
            _ZERG_DRONE,
            _ZERG_DRONEBURROWED,
            _ZERG_EGG,
            _ZERG_EVOLUTIONCHAMBER,
            _ZERG_EXTRACTOR,
            _ZERG_GREATERSPIRE,
            _ZERG_HATCHERY,
            _ZERG_HIVE,
            _ZERG_HYDRALISK,
            _ZERG_HYDRALISKBURROWED,
            _ZERG_HYDRALISKDEN,
            _ZERG_INFESTATIONPIT,
            _ZERG_INFESTEDTERRANSEGG,
            _ZERG_INFESTOR,
            _ZERG_INFESTORBURROWED,
            _ZERG_INFESTORTERRAN,
            _ZERG_LAIR,
            _ZERG_LARVA,
            _ZERG_LOCUSTMP,
            _ZERG_LOCUSTMPFLYING,
            _ZERG_LURKERDENMP,
            _ZERG_LURKERMP,
            _ZERG_LURKERMPBURROWED,
            _ZERG_LURKERMPEGG,
            _ZERG_MUTALISK,
            _ZERG_NYDUSCANAL,
            _ZERG_NYDUSNETWORK,
            _ZERG_OVERLORD,
            _ZERG_OVERLORDCOCOON,
            _ZERG_OVERLORDTRANSPORT,
            _ZERG_OVERSEER,
            _ZERG_QUEEN,
            _ZERG_QUEENBURROWED,
            _ZERG_RAVAGER,
            _ZERG_RAVAGERCOCOON,
            _ZERG_ROACH,
            _ZERG_ROACHBURROWED,
            _ZERG_ROACHWARREN,
            _ZERG_SPAWNINGPOOL,
            _ZERG_SPINECRAWLER,
            _ZERG_SPINECRAWLERUPROOTED,
            _ZERG_SPIRE,
            _ZERG_SPORECRAWLER,
            _ZERG_SPORECRAWLERUPROOTED,
            _ZERG_SWARMHOSTBURROWEDMP,
            _ZERG_SWARMHOSTMP,
            _ZERG_TRANSPORTOVERLORDCOCOON,
            _ZERG_ULTRALISK,
            _ZERG_ULTRALISKCAVERN,
            _ZERG_VIPER,
            _ZERG_ZERGLING,
            _ZERG_ZERGLINGBURROWED,
            _ZERG_PARASITICBOMBDUMMY
        ]

    def protoss(self) -> []:
        return [
            _PROTOSS_ADEPT,
            _PROTOSS_ADEPTPHASESHIFT,
            _PROTOSS_ARCHON,
            _PROTOSS_ASSIMILATOR,
            _PROTOSS_CARRIER,
            _PROTOSS_COLOSSUS,
            _PROTOSS_CYBERNETICSCORE,
            _PROTOSS_DARKSHRINE,
            _PROTOSS_DARKTEMPLAR,
            _PROTOSS_DISRUPTOR,
            _PROTOSS_DISRUPTORPHASED,
            _PROTOSS_FLEETBEACON,
            _PROTOSS_FORGE,
            _PROTOSS_GATEWAY,
            _PROTOSS_HIGHTEMPLAR,
            _PROTOSS_IMMORTAL,
            _PROTOSS_INTERCEPTOR,
            _PROTOSS_MOTHERSHIP,
            _PROTOSS_MOTHERSHIPCORE,
            _PROTOSS_NEXUS,
            _PROTOSS_OBSERVER,
            _PROTOSS_ORACLE,
            _PROTOSS_ORACLESTASISTRAP,
            _PROTOSS_PHOENIX,
            _PROTOSS_PHOTONCANNON,
            _PROTOSS_PROBE,
            _PROTOSS_PYLON,
            _PROTOSS_PYLONOVERCHARGED,
            _PROTOSS_ROBOTICSBAY,
            _PROTOSS_ROBOTICSFACILITY,
            _PROTOSS_SENTRY,
            _PROTOSS_SHIELDBATTERY,
            _PROTOSS_STALKER,
            _PROTOSS_STARGATE,
            _PROTOSS_TEMPEST,
            _PROTOSS_TEMPLARARCHIVE,
            _PROTOSS_TWILIGHTCOUNCIL,
            _PROTOSS_VOIDRAY,
            _PROTOSS_WARPGATE,
            _PROTOSS_WARPPRISM,
            _PROTOSS_WARPPRISMPHASING,
            _PROTOSS_ZEALOT,
        ]
